apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: kcc-config-sync-test-bucket-146316
  namespace: config-control
spec:
  location: us-central1
  uniformBucketLevelAccess: true
